import os
import subprocess
from SSLock import General
import time

def autamated_email_allerts(EMAIL_ENABLE, EMAIL):

    f_exm_conf = '/etc/exim4/update-exim4.conf.conf'
    file_path_1 = '/etc/exim4/passwd.client'
    f_exim_localmacros = '/etc/exim4/exim4.conf.localmacros'
    f_exim_template = '/etc/exim4/exim4.conf.template'
    f_exim_autogenerated = '/var/lib/exim4/config.autogenerated'

    # if not EMAIL_ENABLE: return

    General.run_cmd('apt install exim4 openssl ca-certificates -y')
    General.output_message('Editing configuration files..')
    General.run_cmd('chown root:Debian-exim /etc/exim4/passwd.client')
    General.run_cmd('chown 640 /etc/exim4/passwd.client')

    if not os.path.exists('/usr/share/doc/exim4-base/examples/exim-gencert'):
        General.run_cmd('bash /usr/share/doc/exim4-base/examples/exim-gencert')

    with open(f_exim_localmacros, 'w') as file:
            file.write('''
    MAIN_TLS_ENABLE = 1
    REMOTE_SMTP_SMARTHOST_HOSTS_REQUIRE_TLS = *
    TLS_ON_CONNECT_PORTS = 465
    REQUIRE_PROTOCOL = smtps
    IGNORE_SMTP_LINE_LENGTH_LIMIT = true
                ''')

    General.run_cmd(f'wget -q https://raw.githubusercontent.com/TheeBlind/Exim4_Gmail_conf/master/nconf/config.autogenerated -O {f_exim_autogenerated}')
    General.run_cmd(f'wget -q https://raw.githubusercontent.com/TheeBlind/Exim4_Gmail_conf/master/nconf/exim4.conf.template -O {f_exim_template}')
    General.run_cmd(f'wget -q https://raw.githubusercontent.com/TheeBlind/Exim4_Gmail_conf/master/nconf/update-exim4.conf.conf -O {f_exm_conf}')
    local_ip = subprocess.check_output(['hostname', '-I'], stderr=subprocess.STDOUT)
    local_ip = str(local_ip).strip("b'n\\ ")
    General.change_lines(f_exim_template,
                         _1=[
            '* changeme Ffrs',
            f"* {local_ip}@{General.USER}.{General.HOSTNAME} Ffrs\n"
        ])

    General.change_lines(
        f_exim_autogenerated,
            _1=[
            '* chengeme Ffrs',
            f"* {local_ip}@{General.USER}.{General.HOSTNAME} Ffrs\n"
        ])
    General.run_cmd('update-exim4.conf')
    General.run_cmd('systemctl restart exim4')

    General.run_cmd(f"""echo "Automatic SSlock notification test, if you received this mail, you can go ahead in the setup. if you have received this mail by mistake, please delete it." | mail -s 'Test!' {EMAIL}""")
    General.output_message('Mail setup Completed')
    response = General.answer(f'We have sent a test mail to the address {EMAIL}. Have you recived it?\nCheck the spam folder!')
    if not response:
        General.output_message(
"""
If you received no mail you can check the exim4 logs for investigate about the problem
> sudo cat /var/log/exim4/mainlog
> sudo cat /var/log/exim4/paniclog
> check if something is blocking port 25 out
""")
        time.sleep(5)
